version: "3.7"
services:
    web:
        image: station-ui
        build: .
        ports:
            - "80:80"
        networks:
            sysnet:
        restart: unless-stopped
networks:
    sysnet:
